package nl.ng.projectcargohubapp.strings

object Strings {
    const val baseUrl = "https://cargohubcdm.azurewebsites.net/api/"
    const val location = "location"
    const val Location = "Location"
    const val trackLocation = "Tracking location..."
    const val locationNull = "Location: null"
    const val actionStart = "ACTION_START"
    const val actionStop = "ACTION_STOP"
    const val planned = "PLANNED"
    const val activeTrip = "Active trips"
    const val active = "ACTIVE"
    const val loaded = "LOADED"
    const val closed = "CLOSED"
    const val start = "start"
    const val login = "Login"
    const val image = "Image"
    const val pickupTime = "Pickup time"
    const val timeslot = "Timeslot"
    const val jwt = "jwt"
    const val Bearer = "Bearer"
    const val bearer = "bearer"
    const val imageJpeg = "image/jpeg"
    const val driverId = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/sid"
    const val getTrips = "getTrips"
    const val driverIdNull = "DriverID is null"
    const val unauthorized = "HTTP 401 Unauthorized"
    const val httpException = "HTTP Exception"
    const val unexpectedException = "Unexpected Exception"
    const val getAirwayBills = "getAirwayBills"
    const val getOrders = "getOrders"
    const val updateOrderStatus = "updateOrderStatus"
    const val updateTripStatus = "updateTripStatus"
    const val postImage = "postImage"
    const val updateLocation = "updateLocation"
}